<?php

/**
 * @file
 * Contains ms_registration_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ms_registration_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ms_registration_config module.
    case 'help.page.ms_registration_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module consists of configurations related to registration page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ms_registration_config_theme() {
  return [
    'ms_registration_config' => [
      'render element' => 'children',
    ],
  ];
}
