# Employee Designation routing definition
emp_designation_entity.settings_tab:
  route_name: emp_designation_entity.settings
  title: 'Settings'
  base_route: emp_designation_entity.settings

entity.emp_designation_entity.canonical:
  route_name: entity.emp_designation_entity.canonical
  base_route: entity.emp_designation_entity.canonical
  title: 'View'

entity.emp_designation_entity.edit_form:
  route_name: entity.emp_designation_entity.edit_form
  base_route: entity.emp_designation_entity.canonical
  title: 'Edit'

entity.emp_designation_entity.version_history:
  route_name: entity.emp_designation_entity.version_history
  base_route: entity.emp_designation_entity.canonical
  title: 'Revisions'

entity.emp_designation_entity.delete_form:
  route_name:  entity.emp_designation_entity.delete_form
  base_route:  entity.emp_designation_entity.canonical
  title: Delete
  weight: 10
