add employee designation entities:
  title: 'Create new Employee Designation entities'

administer employee designation entities:
  title: 'Administer Employee Designation entities'
  description: 'Allow to access the administration form to configure Employee Designation entities.'
  restrict access: true

delete employee designation entities:
  title: 'Delete Employee Designation entities'

edit employee designation entities:
  title: 'Edit Employee Designation entities'

view published employee designation entities:
  title: 'View published Employee Designation entities'

view unpublished employee designation entities:
  title: 'View unpublished Employee Designation entities'

view all employee designation revisions:
  title: 'View all Employee Designation revisions'

revert all employee designation revisions:
  title: 'Revert all Employee Designation revisions'
  description: 'Role requires permission <em>view Employee Designation revisions</em> and <em>edit rights</em> for employee designation entities in question or <em>administer employee designation entities</em>.'

delete all employee designation revisions:
  title: 'Delete all revisions'
  description: 'Role requires permission to <em>view Employee Designation revisions</em> and <em>delete rights</em> for employee designation entities in question or <em>administer employee designation entities</em>.'

